[package]
name = "prefix_trie"
version = "0.1.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]

[dependencies]
aster = { path = "../serde/aster" }
quasi = { path = "../serde/quasi/quasi" }
quasi_macros = { path = "../serde/quasi/quasi_macros" }
quickcheck = "*"
